/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coursemanagmentsystem;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Haritha
 */
public class EditCoursePage extends javax.swing.JFrame {

    /**
     * Creates new form EditCoursePage
     */
    
    DefaultTableModel model;
    public EditCoursePage() {
        initComponents();
        setDataToTable();
    }
    Color clrin = new Color(0,0,102);//in color
Color clrout = new Color(51,51,255);//out color

public void setDataToTable()
{
    try {
           Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/feesmanagmentdb","nibm","root");
        PreparedStatement ps = con.prepareStatement("select * from tblcourse");
        ResultSet rs= ps.executeQuery();
        
        while(rs.next())
        {
            int id = rs.getInt("ID");
            String Cname = rs.getString("courseName");
            String Camount = rs.getString("amount");
            String Ctime = rs.getString("time");
            
            Object[] obj ={id,Cname,Camount,Ctime};
            model=(DefaultTableModel)tblCourse.getModel();
            model.addRow(obj);
        }
    }
    
    catch (Exception e) {
        e.printStackTrace();
    }
}

public int getIdNo()
{
    int id = 0;
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/feesmanagmentdb","nibm","root");
        PreparedStatement ps = con.prepareStatement("select max(ID) from tblcourse");
        ResultSet rs =ps.executeQuery();     
        if(rs.next()== true)
        {
            id=rs.getInt(1);            
        }
    } catch (Exception e) {
    }
    return id+1;
}

public void addcourse()
{
    String Cname,Camount,Cduration;
    
    int id=getIdNo();
    Cname=txtCourseName.getText();
    Camount=txtCourseAmount.getText();
    Cduration=txtCourseDuration.getText();
    
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/feesmanagmentdb","nibm","root");
        PreparedStatement ps = con.prepareStatement("insert into tblcourse values(?,?,?,?)");
        ps.setInt(1, id);
        ps.setString(2, Cname);
        ps.setString(3, Camount);
        ps.setString(4, Cduration);
            int rs = ps.executeUpdate();
            if(rs>=1)
            {
                id++;
            }
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelMani = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCourseName = new javax.swing.JTextField();
        txtCourseDuration = new javax.swing.JTextField();
        txtCourseAmount = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourse = new javax.swing.JTable();
        panelSide = new javax.swing.JPanel();
        panelhome = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        paneladdfees = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        panelserchrecord = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panelviewrecord = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        panelviewcourse = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        panelviewreport = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        panelback = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Edit course details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(381, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 110));

        panelMani.setBackground(new java.awt.Color(0, 51, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Course Amount :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Course Duration :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Course Name :");

        txtCourseName.setBackground(new java.awt.Color(255, 255, 255));
        txtCourseName.setForeground(new java.awt.Color(0, 0, 0));
        txtCourseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseNameActionPerformed(evt);
            }
        });

        txtCourseDuration.setBackground(new java.awt.Color(255, 255, 255));
        txtCourseDuration.setForeground(new java.awt.Color(0, 0, 0));

        txtCourseAmount.setBackground(new java.awt.Color(255, 255, 255));
        txtCourseAmount.setForeground(new java.awt.Color(0, 0, 0));

        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setForeground(new java.awt.Color(0, 0, 0));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tblCourse.setBackground(new java.awt.Color(204, 204, 204));
        tblCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Course name", "Amount", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCourseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCourse);
        if (tblCourse.getColumnModel().getColumnCount() > 0) {
            tblCourse.getColumnModel().getColumn(0).setHeaderValue("ID");
            tblCourse.getColumnModel().getColumn(1).setHeaderValue("Course name");
            tblCourse.getColumnModel().getColumn(2).setHeaderValue("Amount");
            tblCourse.getColumnModel().getColumn(3).setHeaderValue("Time");
        }

        javax.swing.GroupLayout panelManiLayout = new javax.swing.GroupLayout(panelMani);
        panelMani.setLayout(panelManiLayout);
        panelManiLayout.setHorizontalGroup(
            panelManiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManiLayout.createSequentialGroup()
                .addGroup(panelManiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelManiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelManiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelManiLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel4))
                            .addGroup(panelManiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addGroup(panelManiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCourseDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCourseAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelManiLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelManiLayout.setVerticalGroup(
            panelManiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManiLayout.createSequentialGroup()
                .addGroup(panelManiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelManiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelManiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(panelManiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCourseAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelManiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCourseDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(panelManiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete)))
                    .addGroup(panelManiLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        getContentPane().add(panelMani, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 780, 410));

        panelSide.setBackground(new java.awt.Color(0, 0, 153));

        panelhome.setBackground(new java.awt.Color(51, 51, 255));
        panelhome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelhomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelhomeMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Home");

        javax.swing.GroupLayout panelhomeLayout = new javax.swing.GroupLayout(panelhome);
        panelhome.setLayout(panelhomeLayout);
        panelhomeLayout.setHorizontalGroup(
            panelhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhomeLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel5)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        panelhomeLayout.setVerticalGroup(
            panelhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelhomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        paneladdfees.setBackground(new java.awt.Color(51, 51, 255));
        paneladdfees.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        paneladdfees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneladdfeesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paneladdfeesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paneladdfeesMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("AddFees");

        javax.swing.GroupLayout paneladdfeesLayout = new javax.swing.GroupLayout(paneladdfees);
        paneladdfees.setLayout(paneladdfeesLayout);
        paneladdfeesLayout.setHorizontalGroup(
            paneladdfeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneladdfeesLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneladdfeesLayout.setVerticalGroup(
            paneladdfeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneladdfeesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        panelserchrecord.setBackground(new java.awt.Color(51, 51, 255));
        panelserchrecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelserchrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelserchrecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelserchrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelserchrecordMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Search Record");

        javax.swing.GroupLayout panelserchrecordLayout = new javax.swing.GroupLayout(panelserchrecord);
        panelserchrecord.setLayout(panelserchrecordLayout);
        panelserchrecordLayout.setHorizontalGroup(
            panelserchrecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelserchrecordLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelserchrecordLayout.setVerticalGroup(
            panelserchrecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelserchrecordLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        panelviewrecord.setBackground(new java.awt.Color(51, 51, 255));
        panelviewrecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelviewrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelviewrecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelviewrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelviewrecordMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("View Record");

        javax.swing.GroupLayout panelviewrecordLayout = new javax.swing.GroupLayout(panelviewrecord);
        panelviewrecord.setLayout(panelviewrecordLayout);
        panelviewrecordLayout.setHorizontalGroup(
            panelviewrecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelviewrecordLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelviewrecordLayout.setVerticalGroup(
            panelviewrecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelviewrecordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelviewcourse.setBackground(new java.awt.Color(51, 51, 255));
        panelviewcourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelviewcourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelviewcourseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelviewcourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelviewcourseMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("View Course");

        javax.swing.GroupLayout panelviewcourseLayout = new javax.swing.GroupLayout(panelviewcourse);
        panelviewcourse.setLayout(panelviewcourseLayout);
        panelviewcourseLayout.setHorizontalGroup(
            panelviewcourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelviewcourseLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelviewcourseLayout.setVerticalGroup(
            panelviewcourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelviewcourseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelviewreport.setBackground(new java.awt.Color(51, 51, 255));
        panelviewreport.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelviewreport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelviewreportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelviewreportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelviewreportMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("View Repord");

        javax.swing.GroupLayout panelviewreportLayout = new javax.swing.GroupLayout(panelviewreport);
        panelviewreport.setLayout(panelviewreportLayout);
        panelviewreportLayout.setHorizontalGroup(
            panelviewreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelviewreportLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelviewreportLayout.setVerticalGroup(
            panelviewreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelviewreportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelback.setBackground(new java.awt.Color(51, 51, 255));
        panelback.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelbackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelbackMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Back");

        javax.swing.GroupLayout panelbackLayout = new javax.swing.GroupLayout(panelback);
        panelback.setLayout(panelbackLayout);
        panelbackLayout.setHorizontalGroup(
            panelbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbackLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelbackLayout.setVerticalGroup(
            panelbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelbackLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelSideLayout = new javax.swing.GroupLayout(panelSide);
        panelSide.setLayout(panelSideLayout);
        panelSideLayout.setHorizontalGroup(
            panelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSideLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelviewreport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelviewcourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelviewrecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelserchrecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneladdfees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelback, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelSideLayout.createSequentialGroup()
                        .addComponent(panelhome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelSideLayout.setVerticalGroup(
            panelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelhome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneladdfees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelserchrecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelviewrecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelviewcourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelviewreport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(panelback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        getContentPane().add(panelSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 190, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseNameActionPerformed

    private void panelhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelhomeMouseClicked
        Homepage home = new Homepage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelhomeMouseClicked

    private void panelhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelhomeMouseEntered
        panelhome.setBackground(clrin);
    }//GEN-LAST:event_panelhomeMouseEntered

    private void panelhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelhomeMouseExited
        panelhome.setBackground(clrout);
    }//GEN-LAST:event_panelhomeMouseExited

    private void paneladdfeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneladdfeesMouseClicked
        AddFeespage add = new AddFeespage();
        add.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_paneladdfeesMouseClicked

    private void paneladdfeesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneladdfeesMouseEntered
        paneladdfees.setBackground(clrin);
    }//GEN-LAST:event_paneladdfeesMouseEntered

    private void paneladdfeesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneladdfeesMouseExited
         paneladdfees.setBackground(clrout);
    }//GEN-LAST:event_paneladdfeesMouseExited

    private void panelserchrecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelserchrecordMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelserchrecordMouseClicked

    private void panelserchrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelserchrecordMouseEntered
        panelserchrecord.setBackground(clrin);
    }//GEN-LAST:event_panelserchrecordMouseEntered

    private void panelserchrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelserchrecordMouseExited
        panelserchrecord.setBackground(clrout);
    }//GEN-LAST:event_panelserchrecordMouseExited

    private void panelviewrecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelviewrecordMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelviewrecordMouseClicked

    private void panelviewrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelviewrecordMouseEntered
        panelviewrecord.setBackground(clrin);
    }//GEN-LAST:event_panelviewrecordMouseEntered

    private void panelviewrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelviewrecordMouseExited
        panelviewrecord.setBackground(clrout);
    }//GEN-LAST:event_panelviewrecordMouseExited

    private void panelviewcourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelviewcourseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelviewcourseMouseClicked

    private void panelviewcourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelviewcourseMouseEntered
        panelviewcourse.setBackground(clrin);
    }//GEN-LAST:event_panelviewcourseMouseEntered

    private void panelviewcourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelviewcourseMouseExited
        panelviewcourse.setBackground(clrout);
    }//GEN-LAST:event_panelviewcourseMouseExited

    private void panelviewreportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelviewreportMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelviewreportMouseClicked

    private void panelviewreportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelviewreportMouseEntered
        panelviewreport.setBackground(clrin);
    }//GEN-LAST:event_panelviewreportMouseEntered

    private void panelviewreportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelviewreportMouseExited
        panelviewreport.setBackground(clrout);
    }//GEN-LAST:event_panelviewreportMouseExited

    private void panelbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelbackMouseClicked
        Homepage home = new Homepage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelbackMouseClicked

    private void panelbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelbackMouseEntered
        panelback.setBackground(clrin);
    }//GEN-LAST:event_panelbackMouseEntered

    private void panelbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelbackMouseExited
        panelback.setBackground(clrout);
    }//GEN-LAST:event_panelbackMouseExited

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addcourse();
        JOptionPane.showMessageDialog(this, "course add to the list");
    }//GEN-LAST:event_btnAddActionPerformed

    private void tblCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCourseMouseClicked
        int rowno =tblCourse.getSelectedRow();
        TableModel model = tblCourse.getModel();
        
        txtCourseName.setText(model.getValueAt(rowno, 1).toString());
        txtCourseAmount.setText(model.getValueAt(rowno, 2).toString());
        txtCourseDuration.setText(model.getValueAt(rowno, 3).toString());
    }//GEN-LAST:event_tblCourseMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            String cname=txtCourseName.getText();
             Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/feesmanagmentdb","nibm","root");
        PreparedStatement ps = con.prepareStatement("delete from tblcourse where courseName=?");
        ps.setString(1, cname);
       
            int rs = ps.executeUpdate();
            
            if(rs==1)
            {
                JOptionPane.showMessageDialog(this, "delete completed");
            }
            else{
                 JOptionPane.showMessageDialog(this, "delete incomplete pleace check");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            String cname=txtCourseName.getText();
            String Camount=txtCourseAmount.getText();
            String Ctime=txtCourseDuration.getText();
            int row=tblCourse.getSelectedRow();
            TableModel model = tblCourse.getModel();
            int id =(int) (model.getValueAt(row, 0));
             Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/feesmanagmentdb","nibm","root");
        PreparedStatement ps = con.prepareStatement("update tblcourse set courseName= ? , amount =? ,time= ? where ID =? ");
        ps.setString(1, cname);
        ps.setString(2, Camount);
        ps.setString(3, Ctime);
         ps.setInt(4, id);
       
            int rs = ps.executeUpdate();
            
            if(rs==1)
            {
                 JOptionPane.showMessageDialog(this, "update completed");
            }
            
            else{
                 JOptionPane.showMessageDialog(this, "update icomplete please chek ");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCoursePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCoursePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCoursePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCoursePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCoursePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelMani;
    private javax.swing.JPanel panelSide;
    private javax.swing.JPanel paneladdfees;
    private javax.swing.JPanel panelback;
    private javax.swing.JPanel panelhome;
    private javax.swing.JPanel panelserchrecord;
    private javax.swing.JPanel panelviewcourse;
    private javax.swing.JPanel panelviewrecord;
    private javax.swing.JPanel panelviewreport;
    private javax.swing.JTable tblCourse;
    private javax.swing.JTextField txtCourseAmount;
    private javax.swing.JTextField txtCourseDuration;
    private javax.swing.JTextField txtCourseName;
    // End of variables declaration//GEN-END:variables
}
