/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coursemanagmentsystem;

import com.mysql.cj.protocol.Resultset;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Haritha
 */
public class PrintResiptPage extends javax.swing.JFrame {

    /**
     * Creates new form PrintResiptPage
     */
    public PrintResiptPage() {
        initComponents();
        getbillinfo();
    }
    Color clrin = new Color(0,0,102);//in color
Color clrout = new Color(51,51,255);//out color


    public void getbillinfo()
    {
        try {
             Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/feesmanagmentdb","nibm","root");
        PreparedStatement ps = con.prepareStatement("SELECT * FROM tblfees ORDER BY billNo DESC LIMIT 1");
            ResultSet rs = ps.executeQuery();
            rs.next();
            
            lblbillno.setText(rs.getString("billNo"));
            lblpaymentmethod.setText(rs.getString("paymentMethod"));
            lblbankname.setText(rs.getString("bankName"));
            lblcardnumber.setText(rs.getString("cardNum"));
            lblchequenumber.setText(rs.getString("chequeNum"));
            lblyear.setText(rs.getString("year"));
            lblsemster.setText(rs.getString("semster"));
            lbldate.setText(rs.getString("date"));
            lblstudentid.setText(rs.getString("studentid"));
            lblstudentname.setText(rs.getString("studentname"));
            lblcoursename.setText(rs.getString("course"));
            lblpaymentdetails.setText(rs.getString("paymentDetails"));
            lbltotalword.setText(rs.getString("totalWord"));
            lbltax.setText(rs.getString("tax"));
            lblregistation.setText(rs.getString("registation"));
            lblamount.setText(rs.getString("amount"));
            lbltotal.setText(rs.getString("total"));
        
        
        
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidepanel = new javax.swing.JPanel();
        panelhome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        paneladdfees = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelserchrecord = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelhome4 = new javax.swing.JPanel();
        panelViewRecord = new javax.swing.JLabel();
        panelEditRecord = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        panelViewCourse = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        paneledit = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        panelprint = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panelbill = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblchequenumber = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        lblpaymentmethod = new javax.swing.JLabel();
        lblbillno = new javax.swing.JLabel();
        lblstudentid = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblbankname = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblcardnumber = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lbltax = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lblstudentname = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lblsemster = new javax.swing.JLabel();
        lblyear = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        lblpaymentdetails = new javax.swing.JLabel();
        lblregistation = new javax.swing.JLabel();
        lbltotalword = new javax.swing.JLabel();
        lblcoursename = new javax.swing.JLabel();
        kk = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        lblamount = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel44 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(0, 0, 153));

        panelhome.setBackground(new java.awt.Color(51, 51, 255));
        panelhome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelhomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelhomeMouseExited(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursemanagmentsystem/icons/icons8-home-50.png"))); // NOI18N
        jLabel1.setText("HOME");

        javax.swing.GroupLayout panelhomeLayout = new javax.swing.GroupLayout(panelhome);
        panelhome.setLayout(panelhomeLayout);
        panelhomeLayout.setHorizontalGroup(
            panelhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelhomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        panelhomeLayout.setVerticalGroup(
            panelhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneladdfees.setBackground(new java.awt.Color(51, 51, 255));
        paneladdfees.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        paneladdfees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneladdfeesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paneladdfeesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paneladdfeesMouseExited(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursemanagmentsystem/icons/add.png"))); // NOI18N
        jLabel3.setText("Add Fees");

        javax.swing.GroupLayout paneladdfeesLayout = new javax.swing.GroupLayout(paneladdfees);
        paneladdfees.setLayout(paneladdfeesLayout);
        paneladdfeesLayout.setHorizontalGroup(
            paneladdfeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneladdfeesLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneladdfeesLayout.setVerticalGroup(
            paneladdfeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneladdfeesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        panelserchrecord.setBackground(new java.awt.Color(51, 51, 255));
        panelserchrecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelserchrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelserchrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelserchrecordMouseExited(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursemanagmentsystem/icons/record.png"))); // NOI18N
        jLabel4.setText("Search record");

        javax.swing.GroupLayout panelserchrecordLayout = new javax.swing.GroupLayout(panelserchrecord);
        panelserchrecord.setLayout(panelserchrecordLayout);
        panelserchrecordLayout.setHorizontalGroup(
            panelserchrecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelserchrecordLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        panelserchrecordLayout.setVerticalGroup(
            panelserchrecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelserchrecordLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        panelhome4.setBackground(new java.awt.Color(51, 51, 255));
        panelhome4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelhome4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelhome4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelhome4MouseExited(evt);
            }
        });

        panelViewRecord.setBackground(new java.awt.Color(255, 255, 255));
        panelViewRecord.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelViewRecord.setForeground(new java.awt.Color(255, 255, 255));
        panelViewRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursemanagmentsystem/icons/view record.png"))); // NOI18N
        panelViewRecord.setText("View record");

        javax.swing.GroupLayout panelhome4Layout = new javax.swing.GroupLayout(panelhome4);
        panelhome4.setLayout(panelhome4Layout);
        panelhome4Layout.setHorizontalGroup(
            panelhome4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhome4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panelViewRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelhome4Layout.setVerticalGroup(
            panelhome4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelhome4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelViewRecord)
                .addContainerGap())
        );

        panelEditRecord.setBackground(new java.awt.Color(51, 51, 255));
        panelEditRecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelEditRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelEditRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelEditRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelEditRecordMouseExited(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursemanagmentsystem/icons/edit.png"))); // NOI18N
        jLabel6.setText("Edit course");

        javax.swing.GroupLayout panelEditRecordLayout = new javax.swing.GroupLayout(panelEditRecord);
        panelEditRecord.setLayout(panelEditRecordLayout);
        panelEditRecordLayout.setHorizontalGroup(
            panelEditRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditRecordLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        panelEditRecordLayout.setVerticalGroup(
            panelEditRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditRecordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelViewCourse.setBackground(new java.awt.Color(51, 51, 255));
        panelViewCourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelViewCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelViewCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelViewCourseMouseExited(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursemanagmentsystem/icons/view record.png"))); // NOI18N
        jLabel7.setText("View course");

        javax.swing.GroupLayout panelViewCourseLayout = new javax.swing.GroupLayout(panelViewCourse);
        panelViewCourse.setLayout(panelViewCourseLayout);
        panelViewCourseLayout.setHorizontalGroup(
            panelViewCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewCourseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        panelViewCourseLayout.setVerticalGroup(
            panelViewCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewCourseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );

        paneledit.setBackground(new java.awt.Color(51, 51, 255));
        paneledit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        paneledit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneleditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paneleditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paneleditMouseExited(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("edit");

        javax.swing.GroupLayout paneleditLayout = new javax.swing.GroupLayout(paneledit);
        paneledit.setLayout(paneleditLayout);
        paneleditLayout.setHorizontalGroup(
            paneleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneleditLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        paneleditLayout.setVerticalGroup(
            paneleditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneleditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelprint.setBackground(new java.awt.Color(51, 51, 255));
        panelprint.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelprint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelprintMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelprintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelprintMouseExited(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("print");

        javax.swing.GroupLayout panelprintLayout = new javax.swing.GroupLayout(panelprint);
        panelprint.setLayout(panelprintLayout);
        panelprintLayout.setHorizontalGroup(
            panelprintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelprintLayout.createSequentialGroup()
                .addGap(0, 63, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelprintLayout.setVerticalGroup(
            panelprintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelprintLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidepanelLayout = new javax.swing.GroupLayout(sidepanel);
        sidepanel.setLayout(sidepanelLayout);
        sidepanelLayout.setHorizontalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelprint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(paneledit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelViewCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelEditRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelhome4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelserchrecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(paneladdfees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelhome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        sidepanelLayout.setVerticalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelhome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paneladdfees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(panelserchrecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelhome4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelEditRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelViewCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(panelprint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paneledit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        getContentPane().add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 720));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelbill.setBackground(new java.awt.Color(255, 255, 255));
        panelbill.setForeground(new java.awt.Color(255, 255, 255));
        panelbill.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 0, 153));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 153));
        panelbill.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 850, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("National Institute of Business Management - Galle Campus. No. 132, Pettigalawatta, Matara Road,Galle.");
        panelbill.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 460, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText(" National Institute of Business Management");
        panelbill.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 380, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Payment Receipt ");
        panelbill.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 160, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("School of Computing");
        panelbill.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 210, -1));

        lblchequenumber.setForeground(new java.awt.Color(0, 0, 0));
        lblchequenumber.setText("--");
        panelbill.add(lblchequenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        lbldate.setForeground(new java.awt.Color(0, 0, 0));
        lbldate.setText("Date :");
        panelbill.add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, -1, -1));

        lblpaymentmethod.setForeground(new java.awt.Color(0, 0, 0));
        lblpaymentmethod.setText("Payment Method :");
        panelbill.add(lblpaymentmethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        lblbillno.setForeground(new java.awt.Color(0, 0, 0));
        lblbillno.setText("Bill NO :");
        panelbill.add(lblbillno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        lblstudentid.setForeground(new java.awt.Color(0, 0, 0));
        lblstudentid.setText("Student ID :");
        panelbill.add(lblstudentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, -1, -1));

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Bill NO :");
        panelbill.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Payment Method :");
        panelbill.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Bank Name :");
        panelbill.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        lblbankname.setForeground(new java.awt.Color(0, 0, 0));
        lblbankname.setText("--");
        panelbill.add(lblbankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Card Number :");
        panelbill.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        lblcardnumber.setForeground(new java.awt.Color(0, 0, 0));
        lblcardnumber.setText("--");
        panelbill.add(lblcardnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Semester");
        panelbill.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        lbltax.setForeground(new java.awt.Color(0, 0, 0));
        lbltax.setText("TAX :");
        panelbill.add(lbltax, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, -1, -1));

        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Student Name :");
        panelbill.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));

        lblstudentname.setForeground(new java.awt.Color(0, 0, 0));
        lblstudentname.setText("Student Name :");
        panelbill.add(lblstudentname, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, -1, -1));

        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Student ID :");
        panelbill.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));

        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Cheque Number :");
        panelbill.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("This payment for :");
        panelbill.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("Year ");
        panelbill.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        lblsemster.setForeground(new java.awt.Color(0, 0, 0));
        lblsemster.setText("jLabel32");
        panelbill.add(lblsemster, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        lblyear.setForeground(new java.awt.Color(0, 0, 0));
        lblyear.setText("jLabel32");
        panelbill.add(lblyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 153));
        panelbill.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 850, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 153));
        panelbill.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 850, 20));

        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Date :");
        panelbill.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, -1, -1));

        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("sr.No");
        panelbill.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Heads");
        panelbill.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Amount");
        panelbill.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, -1, -1));

        lblpaymentdetails.setForeground(new java.awt.Color(0, 0, 0));
        lblpaymentdetails.setText("Payment details :");
        panelbill.add(lblpaymentdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 270, 70));

        lblregistation.setForeground(new java.awt.Color(0, 0, 0));
        lblregistation.setText("Registation Fee :");
        panelbill.add(lblregistation, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, -1, -1));

        lbltotalword.setForeground(new java.awt.Color(0, 0, 0));
        lbltotalword.setText("Total in word :");
        panelbill.add(lbltotalword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, -1, -1));

        lblcoursename.setForeground(new java.awt.Color(0, 0, 0));
        lblcoursename.setText("Course");
        panelbill.add(lblcoursename, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, -1));

        kk.setForeground(new java.awt.Color(0, 0, 0));
        kk.setText("TAX :");
        panelbill.add(kk, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, -1, -1));

        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Course :");
        panelbill.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));

        lblamount.setForeground(new java.awt.Color(0, 0, 0));
        lblamount.setText("Amount :");
        panelbill.add(lblamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, -1, -1));

        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("Registation Fee :");
        panelbill.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, -1, -1));

        lbltotal.setForeground(new java.awt.Color(0, 0, 0));
        lbltotal.setText("Total :");
        panelbill.add(lbltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, -1, -1));

        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("Amount :");
        panelbill.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, -1, -1));

        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("Total :");
        panelbill.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, -1, -1));

        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Payment details :");
        panelbill.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, -1, -1));

        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("signature ");
        panelbill.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 560, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        panelbill.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 550, 240, 10));

        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("Total in word :");
        panelbill.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursemanagmentsystem/icons/nibm logo.jpg"))); // NOI18N
        panelbill.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 210, 90));

        jPanel1.add(panelbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 91, 850, 610));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Print Receipt");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 6, 115, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 880, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelhomeMouseClicked
        Homepage home = new Homepage();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelhomeMouseClicked

    private void panelhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelhomeMouseEntered
        panelhome.setBackground(clrin);
    }//GEN-LAST:event_panelhomeMouseEntered

    private void panelhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelhomeMouseExited
        panelhome.setBackground(clrout);
    }//GEN-LAST:event_panelhomeMouseExited

    private void paneladdfeesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneladdfeesMouseEntered
        paneladdfees.setBackground(clrin);
    }//GEN-LAST:event_paneladdfeesMouseEntered

    private void paneladdfeesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneladdfeesMouseExited
        paneladdfees.setBackground(clrout);        // TODO add your handling code here:
    }//GEN-LAST:event_paneladdfeesMouseExited

    private void panelserchrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelserchrecordMouseEntered
        panelserchrecord.setBackground(clrin);        // TODO add your handling code here:
    }//GEN-LAST:event_panelserchrecordMouseEntered

    private void panelserchrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelserchrecordMouseExited
        panelserchrecord.setBackground(clrout);        // TODO add your handling code here:
    }//GEN-LAST:event_panelserchrecordMouseExited

    private void panelhome4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelhome4MouseEntered
        panelhome4.setBackground(clrin);        // TODO add your handling code here:
    }//GEN-LAST:event_panelhome4MouseEntered

    private void panelhome4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelhome4MouseExited
        panelhome4.setBackground(clrout);
    }//GEN-LAST:event_panelhome4MouseExited

    private void panelEditRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEditRecordMouseClicked
        EditCoursePage edit = new EditCoursePage();
        edit.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelEditRecordMouseClicked

    private void panelEditRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEditRecordMouseEntered
        panelEditRecord.setBackground(clrin);        // TODO add your handling code here:
    }//GEN-LAST:event_panelEditRecordMouseEntered

    private void panelEditRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEditRecordMouseExited
        panelEditRecord.setBackground(clrout);        // TODO add your handling code here:
    }//GEN-LAST:event_panelEditRecordMouseExited

    private void panelViewCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelViewCourseMouseEntered
        panelViewCourse.setBackground(clrin);        // TODO add your handling code here:
    }//GEN-LAST:event_panelViewCourseMouseEntered

    private void panelViewCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelViewCourseMouseExited
        panelViewCourse.setBackground(clrout);        // TODO add your handling code here:
    }//GEN-LAST:event_panelViewCourseMouseExited

    private void paneleditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneleditMouseClicked
        EditBillPage edit = new EditBillPage();
        edit.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_paneleditMouseClicked

    private void paneleditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneleditMouseEntered
        paneledit.setBackground(clrin);        // TODO add your handling code here:
    }//GEN-LAST:event_paneleditMouseEntered

    private void paneleditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneleditMouseExited
        paneledit.setBackground(clrout);        // TODO add your handling code here:
    }//GEN-LAST:event_paneleditMouseExited

    private void panelprintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelprintMouseEntered
        panelprint.setBackground(clrin);        // TODO add your handling code here:
    }//GEN-LAST:event_panelprintMouseEntered

    private void panelprintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelprintMouseExited
        panelprint.setBackground(clrout);        // TODO add your handling code here:
    }//GEN-LAST:event_panelprintMouseExited

    private void panelprintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelprintMouseClicked
        PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
                panelbill.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }
    }//GEN-LAST:event_panelprintMouseClicked

    private void paneladdfeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneladdfeesMouseClicked
        AddFeespage add = new AddFeespage();
        add.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_paneladdfeesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintResiptPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintResiptPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintResiptPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintResiptPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintResiptPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel kk;
    private javax.swing.JLabel lblamount;
    private javax.swing.JLabel lblbankname;
    private javax.swing.JLabel lblbillno;
    private javax.swing.JLabel lblcardnumber;
    private javax.swing.JLabel lblchequenumber;
    private javax.swing.JLabel lblcoursename;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lblpaymentdetails;
    private javax.swing.JLabel lblpaymentmethod;
    private javax.swing.JLabel lblregistation;
    private javax.swing.JLabel lblsemster;
    private javax.swing.JLabel lblstudentid;
    private javax.swing.JLabel lblstudentname;
    private javax.swing.JLabel lbltax;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JLabel lbltotalword;
    private javax.swing.JLabel lblyear;
    private javax.swing.JPanel panelEditRecord;
    private javax.swing.JPanel panelViewCourse;
    private javax.swing.JLabel panelViewRecord;
    private javax.swing.JPanel paneladdfees;
    private javax.swing.JPanel panelbill;
    private javax.swing.JPanel paneledit;
    private javax.swing.JPanel panelhome;
    private javax.swing.JPanel panelhome4;
    private javax.swing.JPanel panelprint;
    private javax.swing.JPanel panelserchrecord;
    private javax.swing.JPanel sidepanel;
    // End of variables declaration//GEN-END:variables
}
